### ISSUE TITLE
Can't install in Laravel 5.5

### ISSUE THREAD

**Issue by jdavidbakr** [faustbrian/Laravel-Stripe#12]
I'm trying to install into Laravel 5.5.  The latest release doesn't support 5.5, so I went with dev-master - but composer requires `"graham-campbell/manager": "^2.4"` - it needs to require `"graham-campbell/manager": "^3.0"` for Laravel 5.5 per https://github.com/GrahamCampbell/Laravel-Manager/releases

**Comment by faustbrian** [comment]
https://github.com/faustbrian/Laravel-Stripe/releases/tag/2.0.0
